config/routes.rb
Rails.application.routes.draw do
 resources :users, only: [:new, :create, :show]
 resources :sessions, only: [:new, :create, :destroy]
 root 'picture_blogs#index'
 resources :picture_blogs do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture_blog.rb
class PictureBlog < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true, length: {in: 1..140}

  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # has_many :picture_blogs
  has_many :picture_blogs
  has_secure_password
  before_validation { email.downcase! }

  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: true
  validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required

  private
  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/picture_blogs_controller.rb
class PictureBlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def index
    @picture_blogs = PictureBlog.all
  end

  def new
    @picture_blog = PictureBlog.new
  end

  def create
    @picture_blog = current_user.picture_blogs.build(picture_blog_params)
    if params[:back]
      render :new
    else
      if @picture_blog.save
        redirect_to picture_blogs_path, notice: "Created a blog!"
      else
        render :new
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    if @picture_blog.update(picture_blog_params)
      redirect_to picture_blogs_path, notice: "Edited a blog!"
    else
      render :edit
    end
  end

  def destroy
    @picture_blog.destroy
    redirect_to picture_blogs_path, notice:"Delated a blog!"
  end

  def confirm
    @picture_blog = current_user.picture_blogs.build(picture_blog_params)
    render :new if @picture_blog.invalid?
  end

  private
  def picture_blog_params
    params.require(:picture_blog).permit(:title, :content, :user_id, :image, :image_cache)
  end

  def set_blog
    @picture_blog = PictureBlog.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = "Failed login"
      render :new
    end
  end
  
  def destroy
    session.delete(:user_id)
    flash[:notice]= "logout"
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/picture_blogs_helper.rb
module PictureBlogsHelper
  def choose_new_or_edit
    if action_name == 'new'
      confirm_picture_blogs_path
    elsif action_name == 'edit'
      picture_blog_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Facebook🕊Clone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/picture_blogs/_form.html.erb
<%= form_with(model: @picture_blog, local: true ,url: choose_new_or_edit) do |form| %>
  <% if @picture_blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @picture_blog.errors.count %>Errors found</h2>
      <ul>
      <% @picture_blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div class="blog_title">
  <%= form.label :image %>
  <%= form.file_field :image %>
  <%= form.hidden_field :image_cache %>
  </div>
  <%= form.submit "Post a picture" %>
<% end %>
<%= link_to "Go back to list", picture_blogs_path %>

app/views/picture_blogs/confirm.html.erb
<h3>Send the informations below</h3>
<%= form_with(model: @picture_blog, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image %>
  <%= form.hidden_field :image_cache %>

  <p>Title:<%= @picture_blog.title %></p>
  <p>Text:<%= @picture_blog.content %></p>
  <%= form.submit "Register" %>
  <%= form.submit "Back", name: 'back' %>
<% end %>

app/views/picture_blogs/edit.html.erb
<h2>Edit blogs</h2>
<%= render 'form' %>

app/views/picture_blogs/index.html.erb
<h1>List of blogs</h1>
<p><%= notice %></p>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>Poster</th>
    <th>Pic</th>
  </tr>
<% @picture_blogs.each do |picture_blog| %>
  <tr>
    <td><%= picture_blog.title %></td>
    <td><%= picture_blog.content %></td>
    <td><%= picture_blog.user.name %></td>
    <td><%= link_to 'Check the details', picture_blog_path(picture_blog.id) %></td>
    <td><%= link_to "Edit Post", edit_picture_blog_path(picture_blog.id), data: { confirm: 'Are you sure you wanna edit' } %></td>
    <td><%= link_to 'Delete Post', picture_blog_path(picture_blog.id), method: :delete ,data: { confirm: 'Are you sure you wanna delete?' } %></td>
  </tr>
<% end %>
</table>
<br>
<%= link_to 'Post a new photo', new_picture_blog_path %>

app/views/picture_blogs/new.html.erb
<h2>What's on your mind?</h2>
<%= render 'form', picture: @picture_blog %>
<div class="link_button1">
  <%= link_to 'back', picture_blogs_path %>
</div>

app/views/picture_blogs/show.html.erb
<h1>Details screen of blog</h1>
<p>Title: <%= @picture_blog.title %></p>
<p>Text: <%= @picture_blog.content %></p>
<p>Poster: <%= @picture_blog.user.name %></p>
<p id="notice"><%= notice %></p>
<p>
  <strong>Image:</strong>
  <%= image_tag @picture_blog.image.url %>
</p>
<%= link_to 'Edit', edit_picture_blog_path(@picture_blog) %> |
<%= link_to 'Back', picture_blogs_path %>
<%= link_to "Go back to list of blog", picture_blogs_path %>

app/views/users/new.html.erb
<h1>Sign to Facebook_Clone</h1>
<% if @user.errors.any? %>
	<h2><%= pluralize(@user.errors.count, "error") %>Errors、 <%= @user.name %> couldn't register</h2>
		<ul>
		<% @user.errors.full_messages.each do |message| %>
			<li><%= message %></li>
		<% end %>
		</ul>
<% end %>
<%= form_with(model: @user, local: true ) do |f| %>
<ul class="users_form_ul" style="list-style-type: none;" >
  <li>
    <%= f.label "Name" %>
    <%= f.text_field :name %><br><br>
  </li>
  <li>
    <%= f.label "Email address" %>
    <%= f.text_field :email %><br><br>
  </li>
  <li>
    <%= f.label "Password"  %>
    <%= f.password_field :password %><br><br><br>
  </li>
  <li>
    <%= f.label :Password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </li>
  <li>
    <%= f.submit "Create account" %>
  </li>
</ul>
<% end %>

  

app/views/users/show.html.erb
<h1><%= @user.name %>'s page</h1>
<p>💌EmailAddress: <%= @user.email %></p>

<%= link_to "Go to list", picture_blogs_path %>